import Navbar from "@/components/navbar.component";
import type { Metadata, Viewport } from "next";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#3580f6",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

        <div className="container">
          <Navbar/>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
